//
// Generated by JTB 1.3.2
//

package visitor.syntaxtree;

/**
 * Grammar production:
 * clause -> Clause()
 * nodeToken -> "&&"
 * clause1 -> Clause()
 */
public class AndExpression implements Node {
   private Node parent;
   public Clause clause;
   public NodeToken nodeToken;
   public Clause clause1;

   public AndExpression(Clause n0, NodeToken n1, Clause n2) {
      clause = n0;
      if ( clause != null ) clause.setParent(this);
      nodeToken = n1;
      if ( nodeToken != null ) nodeToken.setParent(this);
      clause1 = n2;
      if ( clause1 != null ) clause1.setParent(this);
   }

   public AndExpression(Clause n0, Clause n1) {
      clause = n0;
      if ( clause != null ) clause.setParent(this);
      nodeToken = new NodeToken("&&");
      if ( nodeToken != null ) nodeToken.setParent(this);
      clause1 = n1;
      if ( clause1 != null ) clause1.setParent(this);
   }

   public void accept(visitor.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

