//
// Generated by JTB 1.3.2
//

package visitor.syntaxtree;

/**
 * Grammar production:
 * identifier -> Identifier()
 * nodeToken -> "["
 * expression -> Expression()
 * nodeToken1 -> "]"
 * nodeToken2 -> "="
 * expression1 -> Expression()
 * nodeToken3 -> ";"
 */
public class ArrayAssignmentStatement implements Node {
   private Node parent;
   public Identifier identifier;
   public NodeToken nodeToken;
   public Expression expression;
   public NodeToken nodeToken1;
   public NodeToken nodeToken2;
   public Expression expression1;
   public NodeToken nodeToken3;

   public ArrayAssignmentStatement(Identifier n0, NodeToken n1, Expression n2, NodeToken n3, NodeToken n4, Expression n5, NodeToken n6) {
      identifier = n0;
      if ( identifier != null ) identifier.setParent(this);
      nodeToken = n1;
      if ( nodeToken != null ) nodeToken.setParent(this);
      expression = n2;
      if ( expression != null ) expression.setParent(this);
      nodeToken1 = n3;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      nodeToken2 = n4;
      if ( nodeToken2 != null ) nodeToken2.setParent(this);
      expression1 = n5;
      if ( expression1 != null ) expression1.setParent(this);
      nodeToken3 = n6;
      if ( nodeToken3 != null ) nodeToken3.setParent(this);
   }

   public ArrayAssignmentStatement(Identifier n0, Expression n1, Expression n2) {
      identifier = n0;
      if ( identifier != null ) identifier.setParent(this);
      nodeToken = new NodeToken("[");
      if ( nodeToken != null ) nodeToken.setParent(this);
      expression = n1;
      if ( expression != null ) expression.setParent(this);
      nodeToken1 = new NodeToken("]");
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      nodeToken2 = new NodeToken("=");
      if ( nodeToken2 != null ) nodeToken2.setParent(this);
      expression1 = n2;
      if ( expression1 != null ) expression1.setParent(this);
      nodeToken3 = new NodeToken(";");
      if ( nodeToken3 != null ) nodeToken3.setParent(this);
   }

   public void accept(visitor.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

