//
// Generated by JTB 1.3.2
//

package visitor.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> ","
 * expression -> Expression()
 */
public class ExpressionTerm implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public Expression expression;

   public ExpressionTerm(NodeToken n0, Expression n1) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      expression = n1;
      if ( expression != null ) expression.setParent(this);
   }

   public ExpressionTerm(Expression n0) {
      nodeToken = new NodeToken(",");
      if ( nodeToken != null ) nodeToken.setParent(this);
      expression = n0;
      if ( expression != null ) expression.setParent(this);
   }

   public void accept(visitor.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

