//
// Generated by JTB 1.3.2
//

package visitor.syntaxtree;

/**
 * Grammar production:
 * expression -> Expression()
 * expressionTail -> ExpressionTail()
 */
public class ExpressionList implements Node {
   private Node parent;
   public Expression expression;
   public ExpressionTail expressionTail;

   public ExpressionList(Expression n0, ExpressionTail n1) {
      expression = n0;
      if ( expression != null ) expression.setParent(this);
      expressionTail = n1;
      if ( expressionTail != null ) expressionTail.setParent(this);
   }

   public void accept(visitor.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

