//
// Generated by JTB 1.3.2
//

package visitor.syntaxtree;

/**
 * Grammar production:
 * formalParameter -> FormalParameter()
 * formalParameterTail -> FormalParameterTail()
 */
public class FormalParameterList implements Node {
   private Node parent;
   public FormalParameter formalParameter;
   public FormalParameterTail formalParameterTail;

   public FormalParameterList(FormalParameter n0, FormalParameterTail n1) {
      formalParameter = n0;
      if ( formalParameter != null ) formalParameter.setParent(this);
      formalParameterTail = n1;
      if ( formalParameterTail != null ) formalParameterTail.setParent(this);
   }

   public void accept(visitor.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

