//
// Generated by JTB 1.3.2
//

package visitor.syntaxtree;

/**
 * Grammar production:
 * mainClass -> MainClass()
 * nodeListOptional -> ( TypeDeclaration() )*
 * nodeToken -> <EOF>
 */
public class Goal implements Node {
   private Node parent;
   public MainClass mainClass;
   public NodeListOptional nodeListOptional;
   public NodeToken nodeToken;

   public Goal(MainClass n0, NodeListOptional n1, NodeToken n2) {
      mainClass = n0;
      if ( mainClass != null ) mainClass.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
      nodeToken = n2;
      if ( nodeToken != null ) nodeToken.setParent(this);
   }

   public Goal(MainClass n0, NodeListOptional n1) {
      mainClass = n0;
      if ( mainClass != null ) mainClass.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
      nodeToken = new NodeToken("");
      if ( nodeToken != null ) nodeToken.setParent(this);
   }

   public void accept(visitor.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

