//
// Generated by JTB 1.3.2
//

package visitor.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "if"
 * nodeToken1 -> "("
 * expression -> Expression()
 * nodeToken2 -> ")"
 * statement -> Statement()
 * nodeToken3 -> "else"
 * statement1 -> Statement()
 */
public class IfStatement implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public Expression expression;
   public NodeToken nodeToken2;
   public Statement statement;
   public NodeToken nodeToken3;
   public Statement statement1;

   public IfStatement(NodeToken n0, NodeToken n1, Expression n2, NodeToken n3, Statement n4, NodeToken n5, Statement n6) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = n1;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      expression = n2;
      if ( expression != null ) expression.setParent(this);
      nodeToken2 = n3;
      if ( nodeToken2 != null ) nodeToken2.setParent(this);
      statement = n4;
      if ( statement != null ) statement.setParent(this);
      nodeToken3 = n5;
      if ( nodeToken3 != null ) nodeToken3.setParent(this);
      statement1 = n6;
      if ( statement1 != null ) statement1.setParent(this);
   }

   public IfStatement(Expression n0, Statement n1, Statement n2) {
      nodeToken = new NodeToken("if");
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = new NodeToken("(");
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      expression = n0;
      if ( expression != null ) expression.setParent(this);
      nodeToken2 = new NodeToken(")");
      if ( nodeToken2 != null ) nodeToken2.setParent(this);
      statement = n1;
      if ( statement != null ) statement.setParent(this);
      nodeToken3 = new NodeToken("else");
      if ( nodeToken3 != null ) nodeToken3.setParent(this);
      statement1 = n2;
      if ( statement1 != null ) statement1.setParent(this);
   }

   public void accept(visitor.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

