//
// Generated by JTB 1.3.2
//

package visitor.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(visitor.visitor.Visitor v);
   public <R,A> R accept(visitor.visitor.GJVisitor<R,A> v, A argu);
   public <R> R accept(visitor.visitor.GJNoArguVisitor<R> v);
   public <A> void accept(visitor.visitor.GJVoidVisitor<A> v, A argu);
   // It is the responsibility of each implementing class to call
   // setParent() on each of its child Nodes.
   public void setParent(Node n);
   public Node getParent();
}

