//
// Generated by JTB 1.3.2
//

package visitor.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "!"
 * clause -> Clause()
 */
public class NotExpression implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public Clause clause;

   public NotExpression(NodeToken n0, Clause n1) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      clause = n1;
      if ( clause != null ) clause.setParent(this);
   }

   public NotExpression(Clause n0) {
      nodeToken = new NodeToken("!");
      if ( nodeToken != null ) nodeToken.setParent(this);
      clause = n0;
      if ( clause != null ) clause.setParent(this);
   }

   public void accept(visitor.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

