//
// Generated by JTB 1.3.2
//

package visitor.visitor;
import visitor.syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJVoidDepthFirst<A> implements GJVoidVisitor<A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n, A argu) {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
      }
   }

   public void visit(NodeOptional n, A argu) {
      if ( n.present() )
         n.node.accept(this,argu);
   }

   public void visit(NodeSequence n, A argu) {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeToken n, A argu) {}

   //
   // User-generated visitor methods below
   //

   /**
    * mainClass -> MainClass()
    * nodeListOptional -> ( TypeDeclaration() )*
    * nodeToken -> <EOF>
    */
   public void visit(Goal n, A argu) {
      n.mainClass.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeToken2 -> "public"
    * nodeToken3 -> "static"
    * nodeToken4 -> "void"
    * nodeToken5 -> "main"
    * nodeToken6 -> "("
    * nodeToken7 -> "String"
    * nodeToken8 -> "["
    * nodeToken9 -> "]"
    * identifier1 -> Identifier()
    * nodeToken10 -> ")"
    * nodeToken11 -> "{"
    * nodeListOptional -> ( VarDeclaration() )*
    * nodeListOptional1 -> ( Statement() )*
    * nodeToken12 -> "}"
    * nodeToken13 -> "}"
    */
   public void visit(MainClass n, A argu) {
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      n.nodeToken3.accept(this, argu);
      n.nodeToken4.accept(this, argu);
      n.nodeToken5.accept(this, argu);
      n.nodeToken6.accept(this, argu);
      n.nodeToken7.accept(this, argu);
      n.nodeToken8.accept(this, argu);
      n.nodeToken9.accept(this, argu);
      n.identifier1.accept(this, argu);
      n.nodeToken10.accept(this, argu);
      n.nodeToken11.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeListOptional1.accept(this, argu);
      n.nodeToken12.accept(this, argu);
      n.nodeToken13.accept(this, argu);
   }

   /**
    * nodeChoice -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public void visit(TypeDeclaration n, A argu) {
      n.nodeChoice.accept(this, argu);
   }

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeListOptional -> ( VarDeclaration() )*
    * nodeListOptional1 -> ( MethodDeclaration() )*
    * nodeToken2 -> "}"
    */
   public void visit(ClassDeclaration n, A argu) {
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeListOptional1.accept(this, argu);
      n.nodeToken2.accept(this, argu);
   }

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "extends"
    * identifier1 -> Identifier()
    * nodeToken2 -> "{"
    * nodeListOptional -> ( VarDeclaration() )*
    * nodeListOptional1 -> ( MethodDeclaration() )*
    * nodeToken3 -> "}"
    */
   public void visit(ClassExtendsDeclaration n, A argu) {
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.identifier1.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeListOptional1.accept(this, argu);
      n.nodeToken3.accept(this, argu);
   }

   /**
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken -> ";"
    */
   public void visit(VarDeclaration n, A argu) {
      n.type.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "public"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( FormalParameterList() )?
    * nodeToken2 -> ")"
    * nodeToken3 -> "{"
    * nodeListOptional -> ( VarDeclaration() )*
    * nodeListOptional1 -> ( Statement() )*
    * nodeToken4 -> "return"
    * expression -> Expression()
    * nodeToken5 -> ";"
    * nodeToken6 -> "}"
    */
   public void visit(MethodDeclaration n, A argu) {
      n.nodeToken.accept(this, argu);
      n.type.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeOptional.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      n.nodeToken3.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeListOptional1.accept(this, argu);
      n.nodeToken4.accept(this, argu);
      n.expression.accept(this, argu);
      n.nodeToken5.accept(this, argu);
      n.nodeToken6.accept(this, argu);
   }

   /**
    * formalParameter -> FormalParameter()
    * formalParameterTail -> FormalParameterTail()
    */
   public void visit(FormalParameterList n, A argu) {
      n.formalParameter.accept(this, argu);
      n.formalParameterTail.accept(this, argu);
   }

   /**
    * type -> Type()
    * identifier -> Identifier()
    */
   public void visit(FormalParameter n, A argu) {
      n.type.accept(this, argu);
      n.identifier.accept(this, argu);
   }

   /**
    * nodeListOptional -> ( FormalParameterTerm() )*
    */
   public void visit(FormalParameterTail n, A argu) {
      n.nodeListOptional.accept(this, argu);
   }

   /**
    * nodeToken -> ","
    * formalParameter -> FormalParameter()
    */
   public void visit(FormalParameterTerm n, A argu) {
      n.nodeToken.accept(this, argu);
      n.formalParameter.accept(this, argu);
   }

   /**
    * nodeChoice -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public void visit(Type n, A argu) {
      n.nodeChoice.accept(this, argu);
   }

   /**
    * nodeToken -> "int"
    * nodeToken1 -> "["
    * nodeToken2 -> "]"
    */
   public void visit(ArrayType n, A argu) {
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeToken2.accept(this, argu);
   }

   /**
    * nodeToken -> "boolean"
    */
   public void visit(BooleanType n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "int"
    */
   public void visit(IntegerType n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeChoice -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public void visit(Statement n, A argu) {
      n.nodeChoice.accept(this, argu);
   }

   /**
    * nodeToken -> "{"
    * nodeListOptional -> ( Statement() )*
    * nodeToken1 -> "}"
    */
   public void visit(Block n, A argu) {
      n.nodeToken.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeToken1.accept(this, argu);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "="
    * expression -> Expression()
    * nodeToken1 -> ";"
    */
   public void visit(AssignmentStatement n, A argu) {
      n.identifier.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.expression.accept(this, argu);
      n.nodeToken1.accept(this, argu);
   }

   /**
    * identifier -> Identifier()
    * nodeToken -> "["
    * expression -> Expression()
    * nodeToken1 -> "]"
    * nodeToken2 -> "="
    * expression1 -> Expression()
    * nodeToken3 -> ";"
    */
   public void visit(ArrayAssignmentStatement n, A argu) {
      n.identifier.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.expression.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      n.expression1.accept(this, argu);
      n.nodeToken3.accept(this, argu);
   }

   /**
    * nodeToken -> "if"
    * nodeToken1 -> "("
    * expression -> Expression()
    * nodeToken2 -> ")"
    * statement -> Statement()
    * nodeToken3 -> "else"
    * statement1 -> Statement()
    */
   public void visit(IfStatement n, A argu) {
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.expression.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      n.statement.accept(this, argu);
      n.nodeToken3.accept(this, argu);
      n.statement1.accept(this, argu);
   }

   /**
    * nodeToken -> "while"
    * nodeToken1 -> "("
    * expression -> Expression()
    * nodeToken2 -> ")"
    * statement -> Statement()
    */
   public void visit(WhileStatement n, A argu) {
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.expression.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      n.statement.accept(this, argu);
   }

   /**
    * nodeToken -> "System.out.println"
    * nodeToken1 -> "("
    * expression -> Expression()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(PrintStatement n, A argu) {
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.expression.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      n.nodeToken3.accept(this, argu);
   }

   /**
    * nodeChoice -> AndExpression()
    *       | CompareExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | Clause()
    */
   public void visit(Expression n, A argu) {
      n.nodeChoice.accept(this, argu);
   }

   /**
    * clause -> Clause()
    * nodeToken -> "&&"
    * clause1 -> Clause()
    */
   public void visit(AndExpression n, A argu) {
      n.clause.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.clause1.accept(this, argu);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "<"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(CompareExpression n, A argu) {
      n.primaryExpression.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.primaryExpression1.accept(this, argu);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "+"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(PlusExpression n, A argu) {
      n.primaryExpression.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.primaryExpression1.accept(this, argu);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "-"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(MinusExpression n, A argu) {
      n.primaryExpression.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.primaryExpression1.accept(this, argu);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "*"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(TimesExpression n, A argu) {
      n.primaryExpression.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.primaryExpression1.accept(this, argu);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "["
    * primaryExpression1 -> PrimaryExpression()
    * nodeToken1 -> "]"
    */
   public void visit(ArrayLookup n, A argu) {
      n.primaryExpression.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.primaryExpression1.accept(this, argu);
      n.nodeToken1.accept(this, argu);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "."
    * nodeToken1 -> "length"
    */
   public void visit(ArrayLength n, A argu) {
      n.primaryExpression.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
   }

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "."
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( ExpressionList() )?
    * nodeToken2 -> ")"
    */
   public void visit(MessageSend n, A argu) {
      n.primaryExpression.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeOptional.accept(this, argu);
      n.nodeToken2.accept(this, argu);
   }

   /**
    * expression -> Expression()
    * expressionTail -> ExpressionTail()
    */
   public void visit(ExpressionList n, A argu) {
      n.expression.accept(this, argu);
      n.expressionTail.accept(this, argu);
   }

   /**
    * nodeListOptional -> ( ExpressionTerm() )*
    */
   public void visit(ExpressionTail n, A argu) {
      n.nodeListOptional.accept(this, argu);
   }

   /**
    * nodeToken -> ","
    * expression -> Expression()
    */
   public void visit(ExpressionTerm n, A argu) {
      n.nodeToken.accept(this, argu);
      n.expression.accept(this, argu);
   }

   /**
    * nodeChoice -> NotExpression()
    *       | PrimaryExpression()
    */
   public void visit(Clause n, A argu) {
      n.nodeChoice.accept(this, argu);
   }

   /**
    * nodeChoice -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | BracketExpression()
    */
   public void visit(PrimaryExpression n, A argu) {
      n.nodeChoice.accept(this, argu);
   }

   /**
    * nodeToken -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "true"
    */
   public void visit(TrueLiteral n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "false"
    */
   public void visit(FalseLiteral n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> <IDENTIFIER>
    */
   public void visit(Identifier n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "this"
    */
   public void visit(ThisExpression n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "new"
    * nodeToken1 -> "int"
    * nodeToken2 -> "["
    * expression -> Expression()
    * nodeToken3 -> "]"
    */
   public void visit(ArrayAllocationExpression n, A argu) {
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      n.expression.accept(this, argu);
      n.nodeToken3.accept(this, argu);
   }

   /**
    * nodeToken -> "new"
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeToken2 -> ")"
    */
   public void visit(AllocationExpression n, A argu) {
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeToken2.accept(this, argu);
   }

   /**
    * nodeToken -> "!"
    * clause -> Clause()
    */
   public void visit(NotExpression n, A argu) {
      n.nodeToken.accept(this, argu);
      n.clause.accept(this, argu);
   }

   /**
    * nodeToken -> "("
    * expression -> Expression()
    * nodeToken1 -> ")"
    */
   public void visit(BracketExpression n, A argu) {
      n.nodeToken.accept(this, argu);
      n.expression.accept(this, argu);
      n.nodeToken1.accept(this, argu);
   }

}
