//
// Generated by JTB 1.3.2
//

package visitor.visitor;
import visitor.syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * mainClass -> MainClass()
    * nodeListOptional -> ( TypeDeclaration() )*
    * nodeToken -> <EOF>
    */
   public void visit(Goal n);

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeToken2 -> "public"
    * nodeToken3 -> "static"
    * nodeToken4 -> "void"
    * nodeToken5 -> "main"
    * nodeToken6 -> "("
    * nodeToken7 -> "String"
    * nodeToken8 -> "["
    * nodeToken9 -> "]"
    * identifier1 -> Identifier()
    * nodeToken10 -> ")"
    * nodeToken11 -> "{"
    * nodeListOptional -> ( VarDeclaration() )*
    * nodeListOptional1 -> ( Statement() )*
    * nodeToken12 -> "}"
    * nodeToken13 -> "}"
    */
   public void visit(MainClass n);

   /**
    * nodeChoice -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public void visit(TypeDeclaration n);

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "{"
    * nodeListOptional -> ( VarDeclaration() )*
    * nodeListOptional1 -> ( MethodDeclaration() )*
    * nodeToken2 -> "}"
    */
   public void visit(ClassDeclaration n);

   /**
    * nodeToken -> "class"
    * identifier -> Identifier()
    * nodeToken1 -> "extends"
    * identifier1 -> Identifier()
    * nodeToken2 -> "{"
    * nodeListOptional -> ( VarDeclaration() )*
    * nodeListOptional1 -> ( MethodDeclaration() )*
    * nodeToken3 -> "}"
    */
   public void visit(ClassExtendsDeclaration n);

   /**
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken -> ";"
    */
   public void visit(VarDeclaration n);

   /**
    * nodeToken -> "public"
    * type -> Type()
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( FormalParameterList() )?
    * nodeToken2 -> ")"
    * nodeToken3 -> "{"
    * nodeListOptional -> ( VarDeclaration() )*
    * nodeListOptional1 -> ( Statement() )*
    * nodeToken4 -> "return"
    * expression -> Expression()
    * nodeToken5 -> ";"
    * nodeToken6 -> "}"
    */
   public void visit(MethodDeclaration n);

   /**
    * formalParameter -> FormalParameter()
    * formalParameterTail -> FormalParameterTail()
    */
   public void visit(FormalParameterList n);

   /**
    * type -> Type()
    * identifier -> Identifier()
    */
   public void visit(FormalParameter n);

   /**
    * nodeListOptional -> ( FormalParameterTerm() )*
    */
   public void visit(FormalParameterTail n);

   /**
    * nodeToken -> ","
    * formalParameter -> FormalParameter()
    */
   public void visit(FormalParameterTerm n);

   /**
    * nodeChoice -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public void visit(Type n);

   /**
    * nodeToken -> "int"
    * nodeToken1 -> "["
    * nodeToken2 -> "]"
    */
   public void visit(ArrayType n);

   /**
    * nodeToken -> "boolean"
    */
   public void visit(BooleanType n);

   /**
    * nodeToken -> "int"
    */
   public void visit(IntegerType n);

   /**
    * nodeChoice -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public void visit(Statement n);

   /**
    * nodeToken -> "{"
    * nodeListOptional -> ( Statement() )*
    * nodeToken1 -> "}"
    */
   public void visit(Block n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "="
    * expression -> Expression()
    * nodeToken1 -> ";"
    */
   public void visit(AssignmentStatement n);

   /**
    * identifier -> Identifier()
    * nodeToken -> "["
    * expression -> Expression()
    * nodeToken1 -> "]"
    * nodeToken2 -> "="
    * expression1 -> Expression()
    * nodeToken3 -> ";"
    */
   public void visit(ArrayAssignmentStatement n);

   /**
    * nodeToken -> "if"
    * nodeToken1 -> "("
    * expression -> Expression()
    * nodeToken2 -> ")"
    * statement -> Statement()
    * nodeToken3 -> "else"
    * statement1 -> Statement()
    */
   public void visit(IfStatement n);

   /**
    * nodeToken -> "while"
    * nodeToken1 -> "("
    * expression -> Expression()
    * nodeToken2 -> ")"
    * statement -> Statement()
    */
   public void visit(WhileStatement n);

   /**
    * nodeToken -> "System.out.println"
    * nodeToken1 -> "("
    * expression -> Expression()
    * nodeToken2 -> ")"
    * nodeToken3 -> ";"
    */
   public void visit(PrintStatement n);

   /**
    * nodeChoice -> AndExpression()
    *       | CompareExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | Clause()
    */
   public void visit(Expression n);

   /**
    * clause -> Clause()
    * nodeToken -> "&&"
    * clause1 -> Clause()
    */
   public void visit(AndExpression n);

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "<"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(CompareExpression n);

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "+"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(PlusExpression n);

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "-"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(MinusExpression n);

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "*"
    * primaryExpression1 -> PrimaryExpression()
    */
   public void visit(TimesExpression n);

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "["
    * primaryExpression1 -> PrimaryExpression()
    * nodeToken1 -> "]"
    */
   public void visit(ArrayLookup n);

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "."
    * nodeToken1 -> "length"
    */
   public void visit(ArrayLength n);

   /**
    * primaryExpression -> PrimaryExpression()
    * nodeToken -> "."
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeOptional -> ( ExpressionList() )?
    * nodeToken2 -> ")"
    */
   public void visit(MessageSend n);

   /**
    * expression -> Expression()
    * expressionTail -> ExpressionTail()
    */
   public void visit(ExpressionList n);

   /**
    * nodeListOptional -> ( ExpressionTerm() )*
    */
   public void visit(ExpressionTail n);

   /**
    * nodeToken -> ","
    * expression -> Expression()
    */
   public void visit(ExpressionTerm n);

   /**
    * nodeChoice -> NotExpression()
    *       | PrimaryExpression()
    */
   public void visit(Clause n);

   /**
    * nodeChoice -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | BracketExpression()
    */
   public void visit(PrimaryExpression n);

   /**
    * nodeToken -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n);

   /**
    * nodeToken -> "true"
    */
   public void visit(TrueLiteral n);

   /**
    * nodeToken -> "false"
    */
   public void visit(FalseLiteral n);

   /**
    * nodeToken -> <IDENTIFIER>
    */
   public void visit(Identifier n);

   /**
    * nodeToken -> "this"
    */
   public void visit(ThisExpression n);

   /**
    * nodeToken -> "new"
    * nodeToken1 -> "int"
    * nodeToken2 -> "["
    * expression -> Expression()
    * nodeToken3 -> "]"
    */
   public void visit(ArrayAllocationExpression n);

   /**
    * nodeToken -> "new"
    * identifier -> Identifier()
    * nodeToken1 -> "("
    * nodeToken2 -> ")"
    */
   public void visit(AllocationExpression n);

   /**
    * nodeToken -> "!"
    * clause -> Clause()
    */
   public void visit(NotExpression n);

   /**
    * nodeToken -> "("
    * expression -> Expression()
    * nodeToken1 -> ")"
    */
   public void visit(BracketExpression n);

}

